version: '3.8'

services:

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 2003
      POSTGRES_DB: nestdb
    ports:
      - 3005:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
